# ---

# If you want to start adding local datasets manually, rename this template file to `datasets.yml`.

# A dataset record looks like the following:
# example-dataset-id:
#   class: module.Class
#   description: 'Description of the dataset (you can use HTML tags)'
#   enabled: true
#   splits:
#   - list
#   - of
#   - dataset
#   - splits
